routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\TenantController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PermissionController;


Route::get('dashboard',[DashboardController::class,'index'])->name('dashboard');
        
//Write Route for Create Tenant in Master Admin
Route::get('tenant', [TenantController::class,'index'])->name('tenant');
Route::get('tenant/create', [TenantController::class,'create'])->name('tenant-create');
Route::post('tenant/store', [TenantController::class,'store'])->name('tenant-store');
Route::get('tenant/edit/{id}', [TenantController::class,'edit'])->name('tenant-edit');
Route::get('tenant/view/{id}', [TenantController::class,'view'])->name('tenant-view');
Route::put('tenant/mode', [TenantController::class,'changeStatus'])->name('tenant-mode');
Route::post('tenant/update', [TenantController::class,'update'])->name('tenant-update');
Route::delete('tenant/destroy', [TenantController::class,'delete'])->name('tenant-destroy');
Route::get('tenant/show/{id}', [TenantController::class,'show'])->name('tenant-show');
Route::post('tenant/create-database', [TenantController::class,'createDatabase'])->name('tenant-create-batabase');

//Write Route for Create User in Admin
Route::get('user', [UserController::class,'index'])->name('user');
Route::get('user/create', [UserController::class,'create'])->name('user-create');
Route::post('user/store', [UserController::class,'store'])->name('user-store');
Route::get('user/edit/{id}', [UserController::class,'edit'])->name('user-edit');
Route::get('user/view/{id}', [UserController::class,'view'])->name('user-view');
Route::put('user/mode', [UserController::class,'changeStatus'])->name('user-mode');
Route::post('user/update', [UserController::class,'update'])->name('user-update');
Route::delete('user/destroy', [UserController::class,'delete'])->name('user-destroy');
Route::get('user/show/{id}', [UserController::class,'show'])->name('user-show');
Route::get('profile', [UserController::class,'profile'])->name('profile');
Route::post('update-profile', [UserController::class,'updateProfile'])->name('update-profile');
Route::post('change-password', [UserController::class,'changePassword'])->name('change-password');
Route::get('user/getPermission', [UserController::class,'getPermission'])->name('user-get-permission');

//Write Route for Create Role in Admin
Route::get('role', [RoleController::class,'index'])->name('role')->middleware('permission:role_list');
Route::get('role/create', [RoleController::class,'create'])->name('role-create')->middleware('permission:role_create');
Route::post('role/store', [RoleController::class,'store'])->name('role-store')->middleware('permission:role_create');
Route::get('role/edit/{id}', [RoleController::class,'edit'])->name('role-edit')->middleware('permission:role_view');
Route::get('role/view/{id}', [RoleController::class,'view'])->name('role-view')->middleware('permission:role_view');
Route::put('role/mode', [RoleController::class,'changeStatus'])->name('role-mode')->middleware('permission:role_edit');
Route::post('role/update', [RoleController::class,'update'])->name('role-update')->middleware('permission:role_edit');
Route::delete('role/destroy', [RoleController::class,'delete'])->name('role-destroy')->middleware('permission:role_delete');

//Write Route for Create Permission in Admin
Route::get('permission', [PermissionController::class,'index'])->name('permission')->middleware('permission:permission_list');
Route::get('permission/create', [PermissionController::class,'create'])->name('permission-create')->middleware('permission:permission_create');
Route::post('permission/store', [PermissionController::class,'store'])->name('permission-store')->middleware('permission:permission_create');
Route::get('permission/edit/{id}', [PermissionController::class,'edit'])->name('permission-edit')->middleware('permission:permission_view');
Route::get('permission/view/{id}', [PermissionController::class,'view'])->name('permission-view')->middleware('permission:permission_list')->middleware('permission:permission_list');
Route::put('permission/mode', [PermissionController::class,'changeStatus'])->name('permission-mode')->middleware('permission:permission_edit');
Route::post('permission/update', [PermissionController::class,'update'])->name('permission-update')->middleware('permission:permission_edit');
Route::delete('permission/destroy', [PermissionController::class,'delete'])->name('permission-destroy')->middleware('permission:permission_delete');

routes/front.php
<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Auth\FrontAuthConfirmablePasswordController;
use App\Http\Controllers\Auth\EmailVerificationNotificationController;
use App\Http\Controllers\Auth\EmailVerificationPromptController;
use App\Http\Controllers\Auth\NewPasswordController;
use App\Http\Controllers\Auth\PasswordResetLinkController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\Auth\VerifyEmailController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;

Route::get('/register', [RegisteredUserController::class, 'create'])
                ->middleware('guest')
                ->name('front-register');

Route::post('/register', [RegisteredUserController::class, 'store'])
                ->middleware('guest')
                ->name('front-register');

Route::get('/login', [AuthenticatedSessionController::class, 'create'])
                ->middleware('guest')
                ->name('front-login');

Route::post('/login', [AuthenticatedSessionController::class, 'store'])
                ->middleware('guest')
                ->name('front-login');

Route::get('/forgot-password', [PasswordResetLinkController::class, 'create'])
                ->middleware('guest')
                ->name('password.request');

Route::post('/forgot-password', [PasswordResetLinkController::class, 'store'])
                ->middleware('guest')
                ->name('front.password.email');

Route::get('/reset-password/{token}', [NewPasswordController::class, 'create'])
                ->middleware('guest')
                ->name('front.password.reset');

Route::post('/reset-password', [NewPasswordController::class, 'store'])
                ->middleware('guest')
                ->name('front.password.update');

Route::get('/verify-email', [EmailVerificationPromptController::class, '__invoke'])
                //->middleware('auth')
                ->name('verification.notice');

Route::get('/verify-email/{id}/{hash}', [VerifyEmailController::class, '__invoke'])
                ->middleware(['signed', 'throttle:6,1'])
                ->name('verification.verify');

Route::post('/email/verification-notification', [EmailVerificationNotificationController::class, 'store'])
                ->middleware(['auth', 'throttle:6,1'])
                ->name('front.verification.send');

Route::get('/confirm-password', [ConfirmablePasswordController::class, 'show'])
                ->middleware('auth')
                ->name('password.confirm');

Route::post('/confirm-password', [ConfirmablePasswordController::class, 'store'])
                ->middleware('auth');

Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])
                ->middleware('auth')
                ->name('front-logout');

///////////////After login route////////////////////

Route::group(['middleware'=>['auth','tenantverified']],function(){
    Route::get('dashboard', [DashboardController::class,'index'])->name('dashboard');

});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

///////////ROUTE FOR TENANT////////////
Route::domain('{subdomain_name}.localhost.com')->name('tenant.')->middleware('tenant')->namespace('App\Http\Controllers\Tenant')->group(function ($router) {
	require __DIR__.'/tenant.php';
});

Route::domain(env('SITE_URL'))->group(function ($router) {
	///////////////////ROUTE FOR FROUNTSIDE/////////////////////
	Route::get('/', function () {
		return view('frontend/welcome');
	});
	require __DIR__.'/front.php';

	////////////////////ROUTE FOR SUPER ADMIN/////////////////////
	Route::get('/admin', function () {
		if (Auth::check() && Auth::User()->is_admin ==1) {
	    	//return Redirect('admin/dashboard');
		} else {   
			return view('auth.login');	
		}
	});

	//Master Admin Auth Route
	Route::group(array('namespace'=>'Admin', 'prefix' => 'admin'), function(){
		require __DIR__.'/auth.php'; //This route are used in without login in master admin panel.
	});

	Route::group(array('middleware'=>['admin.auth','verified'],'namespace'=>'Admin', 'prefix' => 'admin'), function(){
		require __DIR__.'/admin.php'; 
	});
});

resources/views/layouts-tenant/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            <header class="bg-white shadow">
                <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                    {{ $header }}
                </div>
            </header>

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts-tenant/content.blade.php
@yield('content')

resources/views/layouts-tenant/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.1.0
    </div>
  </footer>

resources/views/layouts-tenant/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts-tenant/header-bar.blade.php
<!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{route('tenant.dashboard',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link">Home</a>
      </li>
      
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <!--<li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>-->

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>

      <li class="nav-item">
          <form method="POST" action="{{route('tenant.logout',['subdomain_name'=>Request::route('subdomain_name')])}}">
             @csrf
              
                <button class="btn" type="submit" title="Click to logout system">
                  Logout
                </button>
          </form>
        
      </li>
      
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/layouts-tenant/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{csrf_token()}}" />
    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Google Font: Source Sans Pro -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="{{asset('assets/plugins/fontawesome-free/css/all.min.css')}}">
      <!-- Daterange picker -->
      <link rel="stylesheet" href="{{asset('assets/plugins/daterangepicker/daterangepicker.css')}}">
      <!-- Select2 -->
      <link rel="stylesheet" href="{{asset('assets/plugins/select2/css/select2.min.css')}}">
      <link rel="stylesheet" href="{{asset('assets/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
      <!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{{asset('assets/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap/-4.min.css')}}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{{asset('assets/dist/css/adminlte.min.css')}}">
      <!-- overlayScrollbars -->
      <link rel="stylesheet" href="{{asset('assets/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')}}">
      <!-- jQuery -->
        <script src="{{asset('assets/plugins/jquery/jquery.min.js')}}"></script>
        <!-- jQuery UI 1.11.4 -->
        <script src="{{asset('assets/plugins/jquery-ui/jquery-ui.min.js')}}"></script>
        <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
        <script>
          $.widget.bridge('uibutton', $.ui.button)
        </script>
        <!-- Bootstrap 4 -->
        <script src="{{asset('assets/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
        <script src="{{asset('assets/plugins/select2/js/select2.full.min.js')}}"></script>
        <!-- InputMask -->
        <script src="{{asset('assets/plugins/moment/moment.min.js')}}"></script>
        <script src="{{asset('assets/plugins/inputmask/jquery.inputmask.min.js')}}"></script>
        <!-- Select2 -->
        <script src="{{asset('assets/plugins/select2/js/select2.full.min.js')}}"></script>
        <!-- daterangepicker -->
        <script src="{{asset('assets/plugins/daterangepicker/daterangepicker.js')}}"></script>
        
        <!-- overlayScrollbars -->
        <script src="{{asset('assets/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js')}}"></script>
        <!-- AdminLTE App -->
        <script src="{{asset('assets/dist/js/adminlte.js')}}"></script>
        <!-- jquery-validation -->
      <script src="{{asset('assets/plugins/jquery-validation/jquery.validate.min.js')}}"></script>
      <script src="{{asset('assets/plugins/jquery-validation/additional-methods.min.js')}}"></script>
      <!-- Tempusdominus Bootstrap 4 -->
      <script src="{{asset('assets/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js')}}"></script>
      <!-- gritter notification css -->
      <link href="{{asset('assets/plugins/gritter/jquery.gritter.css')}}" rel="stylesheet">
      <link href="{{asset('assets/plugins/gritter/jquery.growl.css')}}" rel="stylesheet">
      
      <!-- gritter notification Scripts -->
      <script src="{{asset('assets/plugins/gritter/gritter.min.js')}}"></script>
  	  <!-- smart-wizard for property page -->
  <script type="text/javascript" >
	    /**
     * Gritter notifications when user does something
     *
     * E.g. alertGritter('Restaurants', 'Request for listing restaurants failed', 'growl-error');
     *
     * @param title = title of the popup
     * @param content = content inside popup
     * @param status = 'growl-error', 'growl-success', 'growl-warning' etc.
     */
    function alertGritter(title, content, status) {
        $.gritter.add({
            title: title,
            text: content,
            class_name: status,
            sticky: false,
            time: ''
        });
    }

	</script>
    @if(Session::has('message'))
    <script type="text/javascript" >
    	alertGritter( <?php echo Session::get('module');  ?>, <?php echo Session::get('message');  ?>, <?php echo Session::get('alert-class'); ?> );
	</script>	
    @endif
  </head>
  
  

resources/views/layouts-tenant/left-panel.blade.php
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{route('tenant.dashboard',['subdomain_name'=>Request::route('subdomain_name')])}}" class="brand-link">
      @php
        $image =  asset('storage/no-image-available.png');
        if(!empty(domainDetail()->logo)) {
          $image = asset('storage/'.domainDetail()->logo);
        }
      @endphp
      <img src="{{$image}}" alt="{{isset(domainDetail()->name) ? domainDetail()->name : config('app.name')}}" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">{{isset(domainDetail()->name) ? domainDetail()->name : config('app.name')}}</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        @php
          $image =  asset('storage/no-image-available.png');
          if(!empty(Auth::user()->profile_image)) {
            $image = asset('storage/'.Auth::user()->profile_image);
          }
        @endphp
        <div class="image">
          <img src="{{$image}}" class="img-circle elevation-2" alt="{{Auth::user()->name}}">
        </div>
        <div class="info">
          <a href="{{route('tenant.profile',['subdomain_name'=>Request::route('subdomain_name')])}}" class="d-block">{{Auth::user()->name}}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <!-- <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div> -->

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item">
            <a href="{{route('tenant.dashboard',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('dashboard') ? 'active' : '' }} {{ Request::is('dashboard/profile') ? 'active' : '' }}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>
          @can('user_list')
          <li class="nav-item">
            <a href="{{route('tenant.user',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('user') ? 'active' : '' }} {{ Request::is('user/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-user"></i>
              <p>
                Manage Users
              </p>
            </a>
          </li>
          @endcan
          @can('role_list')
          <li class="nav-item">
            <a href="{{route('tenant.role',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('role') ? 'active' : '' }} {{ Request::is('role/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-lock"></i>
              <p>
                Manage Roles
              </p>
            </a>
          </li>
          @endcan
          @can('stage_list')
          <li class="nav-item">
            <a href="{{route('tenant.stage',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('stage') ? 'active' : '' }} {{ Request::is('stage/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-file-export"></i>
              <p>
                Manage Stages
              </p>
            </a>
          </li>
          @endcan
          @can('contact_list')
          <li class="nav-item">
            <a href="{{route('tenant.contact',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('contact') ? 'active' : '' }} {{ Request::is('contact/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-address-book"></i>
              <p>
                Manage Contacts
              </p>
            </a>
          </li>
          @endcan
          @can('product_list')
          <li class="nav-item">
            <a href="{{route('tenant.product',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('product') ? 'active' : '' }} {{ Request::is('product/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-list"></i>
              <p>
                Manage Products
              </p>
            </a>
          </li>
          @endcan
          @can('lead_list')
          <li class="nav-item">
            <a href="{{route('tenant.lead',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('lead') ? 'active' : '' }} {{ Request::is('lead/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-table"></i>
              <p>
                Manage Leads
              </p>
            </a>
          </li>
          @endcan
          @can('deal_list')
          <li class="nav-item">
            <a href="{{route('tenant.role',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('deal') ? 'active' : '' }} {{ Request::is('deal/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-calendar-week"></i>
              <p>
                Manage Deals
              </p>
            </a>
          </li>
          @endcan
          @can('report_list')
          <li class="nav-item">
            <a href="{{route('tenant.role',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('report') ? 'active' : '' }} {{ Request::is('report/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-download"></i>
              <p>
                Reports Generation
              </p>
            </a>
          </li>
          @endcan
          @can('notification_list')
          <li class="nav-item">
            <a href="{{route('tenant.role',['subdomain_name'=>Request::route('subdomain_name')])}}" class="nav-link {{ Request::is('notification') ? 'active' : '' }} {{ Request::is('notification/*') ? 'active' : '' }}">
              <i class="nav-icon fas fa-comment-dots"></i>
              <p>
                Notifications & Alert Management
              </p>
            </a>
          </li>
          @endcan
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

resources/views/layouts-tenant/master.blade.php
@include('layouts-tenant.header')
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">
	<!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>
  	
    @include('layouts-tenant.header-bar')
 	  @include('layouts-tenant.left-panel')   
    @include('layouts-tenant.content')
    @include('layouts-tenant.footer') 
</div>
</body>
</html>